/**
 * /api/ai/podcasts/[id]/chat — "talk with the hosts" (Phase 4).
 *
 * Reuses the AskChat streaming contract but grounds the answer in the
 * episode's transcript (not the source document). The system prompt is
 * generated by `packages/ai` style helpers so output is identical to the
 * in-process path; we accept a custom `systemOverride` to inject the
 * episode transcript as the source.
 *
 * Per TESTING.md §7 the response cites the transcript line via the same
 * `[cite:p:s]` rule, validated by `validateCitations`.
 */

import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { buildAskPrompt, validateCitations, type AiMessage } from "@readmaxxing/ai";
import { PrismaClient } from "@readmaxxing/db";
import { dispatchAiStream } from "@/lib/ai/worker-bridge";
import { log, newRequestId, readUserId, userIdHash } from "@/lib/observability";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

let prisma: PrismaClient | null = null;
function db(): PrismaClient {
  if (!prisma) prisma = new PrismaClient();
  return prisma;
}

const PostBody = z.object({
  question: z.string().min(1).max(2_000),
  stream: z.boolean().default(true),
});

interface ScriptLine {
  speaker?: string;
  text?: string;
}

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } },
): Promise<Response> {
  const requestId = newRequestId();
  const userId = readUserId(request.headers);
  if (!userId) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  let body: z.infer<typeof PostBody>;
  try {
    body = PostBody.parse(await request.json());
  } catch (err) {
    return NextResponse.json(
      { error: "invalid_request", message: (err as Error).message },
      { status: 400 },
    );
  }

  const episode = await db().podcastEpisode.findFirst({
    where: { id: params.id, userId },
    select: {
      id: true,
      title: true,
      script: true,
      status: true,
    },
  });
  if (!episode) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }
  if (episode.status !== "completed") {
    return NextResponse.json(
      { error: "not_ready", status: episode.status },
      { status: 409 },
    );
  }

  // Build a transcript-shaped source text from the script rows so the
  // `[cite:p:s]` rule can resolve against the lines. The user is talking
  // to the "hosts" (the speakers), so we frame the document as a
  // transcript.
  const script = (episode.script as unknown as ScriptLine[]) ?? [];
  const transcriptText = script
    .map((line, idx) => `[${idx}] ${line.speaker ?? "H1"}: ${line.text ?? ""}`)
    .join("\n");

  const baseFields = {
    request_id: requestId,
    user_id_hash: userIdHash(userId),
    task: "ask" as const,
    document_id: params.id,
    route: "podcast-chat",
  };

  // Reuse the AskChat prompt builder so the citation rule is identical;
  // the only difference is the "document" we hand it.
  const { system, prompt } = buildAskPrompt({
    documentText: transcriptText || episode.title,
    question: `Episode: ${episode.title}\nQuestion: ${body.question}`,
    systemOverride: `You are one of the hosts of the podcast "${episode.title}". Answer the listener's question in the host's voice, grounded in the transcript below. Always cite a transcript line using [cite:lineIndex:sentenceIndex]. If the transcript does not address the question, say so and offer to continue the show on a related thread.\n${transcriptText}`,
  });
  const messages: AiMessage[] = [
    { role: "system", content: system },
    { role: "user", content: prompt },
  ];

  if (body.stream) {
    log.info({ ...baseFields, event: "ai.task_start" });
    const encoder = new TextEncoder();
    const start = Date.now();
    let fullText = "";
    const stream = new ReadableStream<Uint8Array>({
      async start(controller) {
        const enqueue = (obj: unknown): void => {
          try {
            controller.enqueue(encoder.encode(JSON.stringify(obj) + "\n"));
          } catch {
            /* closed */
          }
        };
        enqueue({ meta: { requestId, model: process.env["OPENROUTER_DEFAULT_MODEL"] ?? "openai/gpt-4o-mini" } });
        try {
          const stream = await dispatchAiStream({
            feature: "ask",
            messages,
            userId,
            signal: request.signal,
          });
          for await (const delta of stream) {
            fullText += delta;
            enqueue({ delta });
          }
          const validation = validateCitations(fullText);
          if (validation.missing) {
            log.warn({
              ...baseFields,
              event: "ai.citation_missing",
              prose_length: validation.proseLength,
            });
          }
          log.info({
            ...baseFields,
            event: "ai.task_complete",
            duration_ms: Date.now() - start,
            prose_length: validation.proseLength,
            citation_count: validation.count,
          });
          enqueue({
            done: true,
            citations: validation.anchors ?? [],
            model: process.env["OPENROUTER_DEFAULT_MODEL"] ?? "openai/gpt-4o-mini",
          });
        } catch (err) {
          enqueue({
            error: "ai_failed",
            message: (err as Error).message.slice(0, 200),
          });
          log.error({
            ...baseFields,
            event: "ai.task_failed",
            error_class: (err as Error).name,
            error_msg: (err as Error).message.slice(0, 200),
          });
        } finally {
          try {
            controller.close();
          } catch {
            /* already closed */
          }
        }
      },
    });
    return new Response(stream, {
      headers: {
        "Content-Type": "application/x-ndjson",
        "Transfer-Encoding": "chunked",
        "Cache-Control": "no-store",
      },
    });
  }

  // Non-streaming fallback.
  return NextResponse.json({ error: "non_streaming_unsupported" }, { status: 501 });
}